# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitWorktreeApfs < Formula
  desc "Create Git worktrees using APFS copy-on-write cloning"
  homepage "https://github.com/dannolan/git-worktree-apfs"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dannolan/git-worktree-apfs/releases/download/v0.1.1/git-worktree-apfs_Darwin_x86_64.tar.gz"
      sha256 "04e306bbe3bbb07ff064c0c3d0c392588c0f43075ef76332de6811b7a397130b"

      define_method(:install) do
        bin.install "git-worktree-apfs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dannolan/git-worktree-apfs/releases/download/v0.1.1/git-worktree-apfs_Darwin_arm64.tar.gz"
      sha256 "3c3046faa284d19071d6f87bfd36ba7f35052a463e868cbc55322f3be13f9e2f"

      define_method(:install) do
        bin.install "git-worktree-apfs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dannolan/git-worktree-apfs/releases/download/v0.1.1/git-worktree-apfs_Linux_x86_64.tar.gz"
      sha256 "75e06fca8578d9ea4adeba0fd97fa995b772ae7e3b2213165a772fd8bf0d7149"
      define_method(:install) do
        bin.install "git-worktree-apfs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dannolan/git-worktree-apfs/releases/download/v0.1.1/git-worktree-apfs_Linux_arm64.tar.gz"
      sha256 "955a5d4327f745fa03c6a1a11a2474b18a800ad8a58fee5dbf1a3b1428c4c7e8"
      define_method(:install) do
        bin.install "git-worktree-apfs"
      end
    end
  end

  depends_on :macos

  test do
    assert_match version.to_s, shell_output("#{bin}/git-worktree-apfs version")
    assert_match "git worktree-apfs", shell_output("#{bin}/git-worktree-apfs help")
  end
end
