# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitWorktreeApfs < Formula
  desc "Create Git worktrees using APFS copy-on-write cloning"
  homepage "https://github.com/dannolan/git-worktree-apfs"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dannolan/git-worktree-apfs/releases/download/v0.1.3/git-worktree-apfs_Darwin_x86_64.tar.gz"
      sha256 "aaae2b3b05efcaafcdf15d2d55d4dd8ff6dda61d73fe7313884e05f30c0636db"

      define_method(:install) do
        bin.install "git-worktree-apfs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dannolan/git-worktree-apfs/releases/download/v0.1.3/git-worktree-apfs_Darwin_arm64.tar.gz"
      sha256 "d6bb48fcee5613d3780559a593322fce004566ec381fc079d3b2b795f13bb88d"

      define_method(:install) do
        bin.install "git-worktree-apfs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dannolan/git-worktree-apfs/releases/download/v0.1.3/git-worktree-apfs_Linux_x86_64.tar.gz"
      sha256 "542451d6e895405357751170eafcbbca3bf76b582cffaef3e575d2a82d40bb94"
      define_method(:install) do
        bin.install "git-worktree-apfs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dannolan/git-worktree-apfs/releases/download/v0.1.3/git-worktree-apfs_Linux_arm64.tar.gz"
      sha256 "eb22aacf340485755948c1a7d7f949a06bab8e53a198a59b8d7d64b8d59193cb"
      define_method(:install) do
        bin.install "git-worktree-apfs"
      end
    end
  end

  depends_on :macos

  test do
    assert_match version.to_s, shell_output("#{bin}/git-worktree-apfs version")
    assert_match "git worktree-apfs", shell_output("#{bin}/git-worktree-apfs help")
  end
end
